"""Posts 1 a 12 da super thread: modelos com campos ``{chave}``, nunca algarismo solto.

Cada post: rótulo, título, métrica, legenda da métrica, figura, rodapé de fonte e
parágrafos. ``thread_base.digitos_soltos`` reprova algarismo fora dos campos.
"""

from __future__ import annotations

from . import thread_fig_a as A
from . import thread_fig_b as B

POSTS_A: list[dict] = [
    {
        "tag": "O resultado",
        "tom": "flavio",
        "titulo": "Flávio na frente em toda a noite. E uma noite que o TSE ainda não explicou.",
        "metrica": "{f_pct_n} × {l_pct_n}",
        "metrica_rot": "Flávio × Lula, % dos válidos, {secoes} seções",
        "fig": A.fig_placar,
        "fonte": "TSE, arquivo nacional de presidente gerado às {gerado_final} de {gerado_data}",
        "texto": [
            "O 1º turno de 2026 terminou com Flávio Bolsonaro à frente: {f_votos} votos, {f_pct} dos válidos, contra {l_votos} de Lula, {l_pct}. São {dif_votos} votos de diferença, {dif_pp} ponto. Flávio liderou em todas as {versoes_secoes} versões do arquivo nacional que traziam seções apuradas, da primeira à última. Não houve virada em nenhum minuto da noite.",
            "A terceira via somou {terc_mi} de votos, {terc_pct} dos válidos: Augusto Cury {cury_pct}, Renan Santos {renan_pct}, Ronaldo Caiado {caiado_pct}. O comparecimento foi de {comp_pct}; {abst_mi} de eleitores ficaram em casa. Flávio venceu em {ufs_f} UFs e Lula em {ufs_l}.",
            "Esta thread resume o dossiê da apuração da casa. Ele foi feito só com arquivos públicos do TSE, lidos e guardados versão a versão durante a noite, cada um com a hora em que o tribunal o gerou, a hora em que foi lido e a impressão digital SHA-256. Nada foi digitado à mão: cada número sai de um arquivo de dados que qualquer pessoa pode refazer.",
            "As regras valem para a thread inteira. Verificado é número da urna ou de documento arquivado. Inferência é conta sobre medição publicada. Hipótese é suposição declarada, que pode estar errada. Quando a casa opina, o texto diz juízo editorial. E o achado que contraria a própria tese sai com o mesmo destaque, num post só para ele.",
            "O que o dossiê prova, em poucas linhas. A vantagem de Flávio caiu de {pico_pp} para {final_pp} pontos ao longo da noite pela ordem de chegada dos votos, não por virada. O arquivo nacional de presidente parou {n_paradas} vezes no pico, e por {pausa_min} minutos o TSE não gerou arquivo de resultado de cargo nenhum. As pesquisas erraram a diferença em {erro_comum} pontos a favor de Lula, como em 2022. Nenhuma das {an_topo} zonas mais atípicas do país aponta para fraude. E o 2º turno começa com uma conta que favorece Flávio, desde que ele não perca a própria base.",
            "Os quatro últimos posts tratam do 2º turno: a aritmética, as duas réguas que dizem onde trabalhar, o mapa da militância e as frases para conversar com quem votou em Cury, Renan, Caiado e Zema. Onde há opinião da casa, o texto diz juízo editorial. O dossiê completo, com fonte de cada número, está em brasil.arvor.co.",
        ],
    },
    {
        "tag": "A noite",
        "tom": "flavio",
        "titulo": "A vantagem caiu. A liderança, nunca.",
        "metrica": "{pico_pp} → {final_pp}",
        "metrica_rot": "pontos de vantagem, do pico às {pico_hora} até o fim",
        "fig": A.fig_noite,
        "fonte": "Soma dos arquivos de UF do TSE, minuto a minuto; noite_regioes.json",
        "texto": [
            "Os primeiros votos apareceram às {primeiro_min}. Às {pico_hora}, com {pico_pst} das seções somadas nos arquivos das UFs, Flávio tinha {pico_pp} pontos de vantagem. No fim, {final_pp}. Quem acompanhou a noite viu a vantagem derreter e pensou em virada. Ela não veio: Lula esteve à frente em {lula_minutos} minutos.",
            "Em votos, a vantagem máxima de Flávio foi de {maior_votos}, às {maior_votos_hora}, justamente quando o arquivo nacional estava parado e o painel oficial não mostrava. Às {ne_maior_faltava_hora}, o Nordeste era {ne_maior_faltava} de tudo o que ainda faltava apurar no país. A conta do resto da noite estava escrita ali.",
            "Por que a vantagem caiu? Porque as regiões não chegam juntas. Às {pico_hora}, o Sul representava {sul_apurado_pico} dos votos apurados e terminou com {sul_final} do total. O Nordeste representava {ne_apurado_pico} e terminou com {ne_final}. O voto mais lulista do país chegou depois. A partir das {ne_desde}, o Nordeste passou a pesar mais no que entrava do que pesa no país.",
            "Medimos isso. A linha tracejada do gráfico recoloca cada região no peso final dos válidos, minuto a minuto: é a vantagem que Flávio teria se o país inteiro chegasse ao mesmo tempo. No pico, ela seria de {pico_peso_final} pontos, não {pico_pp}. Da queda total de {queda_pp} pontos, {entre_pp} vêm da ordem de chegada das regiões, {entre_pct} do total. Os outros {dentro_pp} vêm de dentro de cada região, porque ali também o voto de Lula chegou mais tarde.",
            "O fim da noite confirma o desenho. Depois que o país passou de {m99} das seções, às {d99_hora}, entraram {d99_secoes} seções, com Lula a {d99_lula} dos votos dos dois. Depois da meia-noite chegaram {d00_secoes} seções e {d00_validos} votos válidos, Lula a {d00_lula}: aldeias, áreas ribeirinhas e municípios remotos, onde a mídia da urna viaja horas até o ponto de transmissão.",
            "A leitura é simples. A curva que cai é a assinatura de um país que vota em lugares diferentes e transmite em velocidades diferentes. Não é sinal de fraude, e não é sinal de virada. É geografia com relógio. Quem usar a queda da noite como argumento, para um lado ou para o outro, está lendo a ordem de chegada como se fosse resultado.",
            "Para o 2º turno vale o mesmo aviso. A apuração vai começar com o líder mais forte do que termina, porque Sul e Centro-Oeste chegam primeiro e o Nordeste chega por último. Quem comemorar cedo vai se assustar tarde, e quem se assustar cedo vai comemorar tarde.",
        ],
    },
    {
        "tag": "A falha do TSE",
        "tom": "lula",
        "titulo": "O arquivo nacional parou no pico. Por {pausa_min} minutos, nada foi gerado.",
        "metrica": "{pausa_min} min",
        "metrica_rot": "sem nenhum arquivo de resultado, de {pausa_de} a {pausa_ate}",
        "fig": A.fig_falha,
        "fonte": "Banco do coletor da casa; carimbo de recebimento publicado em cada seção pelo TSE",
        "texto": [
            "Verificado nos arquivos públicos. O arquivo nacional de presidente, que alimenta o painel do TSE e os sites de notícia, parou {n_paradas} vezes no pico. De {p1_de} a {p1_ate}, {p1_min} minutos. De {p2_de} a {p2_ate}, {p2_min} minutos, enquanto as seções iam de {p2_pst_de} a {p2_pst_ate}. E de {p3_de} a {p3_ate}, {p3_min} minutos, de {p3_pst_de} a {p3_pst_ate}.",
            "Na parada mais longa, o coletor da casa leu o arquivo {longa_leituras} vezes e recebeu {longa_304} vezes a resposta de que nada tinha mudado. Às {div_hora}, a soma dos arquivos das UFs tinha {div_secoes} seções a mais que o arquivo nacional, {div_pp} do país. O lote que destravou o painel trouxe {longa_secoes} seções e {lote_vv} de votos de uma vez.",
            "Mais grave: de {pausa_de} a {pausa_ate}, o TSE não gerou arquivo de resultado de nenhum cargo, em nenhum nível. Nem presidente, nem governador, nem Senado, nem deputados; nem país, nem UF, nem município. O coletor fez {pausa_leituras} leituras nesse intervalo, {pausa_304} delas com a resposta de não modificado. Só os arquivos de andamento tiveram versão nova, {pausa_ab} deles, numa única rodada.",
            "O carimbo de recebimento que o TSE publica em cada seção some em {n_lacunas_carimbo} janelas que coincidem com as paradas: {c1_de} a {c1_ate}, {c2_de} a {c2_ate} e {c3_de} a {c3_ate}. Antes da pausa geral, entre {des_de} e {des_ate}, os carimbos caíram para {des_razao} do ritmo dos vinte minutos anteriores. É o desenho de uma fila perto da saturação: desacelera, para, volta em rajada.",
            "Durante a parada longa, o painel nacional ficou congelado em {p3_pst_de} das seções enquanto os arquivos das UFs e o próprio andamento do TSE já avançavam. A resposta da casa, ao vivo, foi somar os arquivos das UFs e avisar na tela que o nacional estava atrasado. Quem olhava só o painel oficial via um país parado que não estava parado.",
            "O presidente do TSE atribuiu o atraso a um congestionamento no sistema de divulgação e disse que a totalização não foi afetada. Os arquivos públicos não separam as duas coisas: ou a recepção parou de carimbar, ou o carimbo é aplicado por uma peça posterior que parou junto. Em qualquer caso, a parada não foi só de vitrine. A causa só o relatório técnico do TSE pode dar, e ele ainda não foi publicado.",
        ],
    },
    {
        "tag": "A arquitetura",
        "tom": "outros",
        "titulo": "O volume era pequeno. Se houve gargalo, foi de desenho.",
        "metrica": "{pico_secoes_s} por segundo",
        "metrica_rot": "seções no pico do arquivo nacional",
        "fig": A.fig_arquitetura,
        "fonte": "Nota técnica do TSE de 2020; volumes medidos nos boletins de 2026 (arquitetura.json)",
        "texto": [
            "Em 2020 o TSE centralizou a totalização num banco Oracle sobre equipamento Exadata, e uma nota técnica do próprio tribunal explicou a lentidão daquele ano: o plano de execução do banco tinha sido gerado com as tabelas vazias. A nota falava em mais de {nota_linhas_min} de linhas por minuto. Não há documento que diga qual banco rodou a totalização ou a divulgação em 2026. A explicação pelo banco, portanto, é hipótese do autor, e o dossiê a rotula assim.",
            "O que sabemos é o volume. No pico, o arquivo nacional andou {sust_secoes_min} seções por minuto, cerca de {pico_secoes_s} por segundo. Isso dá {pico_linhas_min} linhas de voto por minuto no auge, {fracao_nota} do que a nota de 2020 citava, e {pico_mb_min} MB de boletins por minuto. Todos os boletins do país somam {bu_total_gb} GB. A parada mais longa represou {represadas_secoes} seções: {represadas_linhas} de linhas e {represadas_gb} GB.",
            "Em 2022, o país inteiro chegou a {r22_pico} boletins por minuto às {r22_pico_hora}, sem parar, e a mediana entre receber e totalizar foi de {r22_p50} segundos. A publicação pesa mais do que a recepção: em 2026 o TSE gerou até {pub_pico_versoes} versões de arquivo por minuto, {pub_pico_mb} MB por minuto. O banco do coletor da casa guarda {versoes_banco} versões desses arquivos num computador de mesa.",
            "Uma ressalva honesta: o portal do TSE limitou o acesso das ferramentas da casa durante a pesquisa, e o anexo da expansão do contrato com a Oracle, listado no portal de contratações, não foi lido. O que está acima é o que os documentos acessíveis provam, e nada além disso.",
            "Juízo editorial. Volume assim cabe em qualquer banco atual. O desenho proporcional é conhecido: cada boletim entra uma vez num registro de eventos que só aceita acréscimo, separado por UF e encadeado por hash; leitores idempotentes processam esse registro; os totais crescem por soma, sem recálculo; e a publicação sai à parte, como fotografia assinada com o número do último evento. Banco distribuído não se justifica pelo volume, só por disponibilidade entre centros de dados.",
            "Para encerrar o assunto, bastam três documentos do TSE: o desenho da totalização e da divulgação de 2026, o registro de eventos da noite com carimbo de recebimento, inclusão e geração de arquivo, e o relatório do incidente.",
        ],
    },
    {
        "tag": "2022 contra 2026",
        "tom": "flavio",
        "titulo": "Flávio cresceu em quase todo lugar, e mais no interior.",
        "metrica": "{margem_virou}",
        "metrica_rot": "pontos que a margem andou para a direita desde 2022",
        "fig": A.fig_regioes,
        "fonte": "TSE 2022 e 2026, 1º turno, por município; presidente.json",
        "texto": [
            "Contra o 1º turno de 2022, Flávio fez {f_swing_pp} pontos e {f_swing_votos} de votos a mais que Bolsonaro. Lula ficou {l_swing_pp} pontos e {l_swing_votos} de votos abaixo de si mesmo. A margem andou {margem_virou} pontos para a direita. Flávio cresceu em {ufs_f_cresceu} das {n_ufs} UFs e em {mun_f_cresceu} de {mun_total} municípios. Lula aumentou a própria fatia em só {mun_l_cresceu} municípios.",
            "A perda de Lula é do Centro-Sul: {cs_perda} de votos, {cs_perda_pct} da perda nacional. No Nordeste, {ne_perda}. O ganho de Flávio, ao contrário, é nacional: {ne_ganho_pct} dele veio do Nordeste, {ne_ganho} de votos. Na região, Flávio fez {ne_flavio} dos válidos, acima até de Bolsonaro no 2º turno de 2022, que teve {ne_bols_2t}.",
            "O gráfico separa capitais e interior, e o padrão é o mesmo nas cinco regiões: Flávio cresceu mais no interior. No Nordeste, {ne_int_f} pontos no interior contra {ne_cap_f} nas capitais, e Lula caiu {ne_int_l} no interior contra {ne_cap_l} nas capitais. No Sudeste, {se_int_f} contra {se_cap_f}. No Sul, {sul_int_f} contra {sul_cap_f}, com Lula a {sul_int_l} no interior. A eleição andou para a direita fora das metrópoles.",
            "Esse é o dado que mais contraria a leitura comum da noite. A queda da vantagem durante a apuração fez parecer que o Nordeste tinha virado o jogo. Não virou. O Nordeste continua lulista, mas menos lulista do que em 2022, e no interior nordestino Flávio já passou a marca de Bolsonaro no 2º turno daquele ano.",
            "A base de Flávio também ficou menos dependente de uma região. O Nordeste tem {ne_validos_parcela} dos válidos do país; ali estão {flavio_ne_parcela} dos votos de Flávio e {lula_ne_parcela} dos de Lula. O voto de Lula é mais concentrado, e o de Flávio, mais espalhado.",
            "O comparecimento ajudou a esconder o movimento. Contra o 1º turno de 2022, ele subiu {comp_ne} ponto no Nordeste e {comp_no} no Norte, e caiu {comp_cs} no Centro-Sul. Nos municípios em que Lula teve de {comp_faixa_rot} em 2022, o comparecimento subiu {comp_faixa} pontos, e mesmo assim Lula perdeu fatia ali. Mais gente votou onde ele era forte, e ele ainda caiu.",
            "Limite: comparar Flávio com Bolsonaro e Lula com Lula mede saldo entre duas eleições, com candidatos e eleitores diferentes. Não diz quem trocou de voto. Contra o 2º turno de 2022, Flávio ainda está {f_vs_b2t} pontos abaixo de Bolsonaro no país. É nessa distância que mora o 2º turno de 2026.",
        ],
    },
    {
        "tag": "O exterior",
        "tom": "lula",
        "titulo": "No exterior, Lula vence e menos gente vai votar.",
        "metrica": "{ext_comp}",
        "metrica_rot": "de comparecimento no exterior; em 2022, {ext_comp_22}",
        "fig": A.fig_exterior,
        "fonte": "TSE, {ext_cidades} cidades em {ext_paises} países; exterior.json",
        "texto": [
            "O voto no exterior foi de Lula: {ext_l} contra {ext_f} de Flávio, uma margem de {ext_margem} votos. Não muda a conta nacional, mas mostra duas coisas que valem para o 2º turno. A primeira é o comparecimento. O eleitorado no exterior foi de {ext_eleitores_22} para {ext_eleitores}, e a taxa de quem votou caiu de {ext_comp_22} para {ext_comp}. Mais gente inscrita, proporcionalmente menos gente na urna.",
            "A segunda é que o exterior não é um bloco. Lula vence com folga na Europa, com {eur_l} dos válidos. Flávio vence na América do Norte, com {an_f}; nos Estados Unidos, com {us_f}; e no Japão, com {jp_f}. Ásia e Américas votam com Flávio; a Europa, com Lula.",
            "No 2º turno de 2022, Bolsonaro teve {ext_b2t} dos válidos no exterior. Flávio fez {ext_f} agora, e a Ásia inteira deu a ele {asia_f}. A distância para a marca de Bolsonaro existe, mas é menor do que o placar sugere: boa parte dela está na Europa, onde Lula é mais forte.",
            "Portugal foi o país que mais andou para Flávio entre os que têm ao menos cinco mil votos válidos: ele fez {pt_f}, {pt_swing} pontos sobre Bolsonaro nas mesmas cidades em 2022, enquanto Lula variou {pt_l_swing}. É a maior comunidade brasileira votante fora do país e a que mais mudou.",
            "Um detalhe técnico que confundiu a noite: o TSE grava a hora de totalização do exterior na hora local de cada cidade. Wellington e Tóquio apareceram como totalizadas no dia seguinte em arquivos gerados no próprio domingo, e o painel nacional exibiu essa data durante horas. Não é fraude nem erro de contagem; é fuso horário impresso sem conversão. Em Moscou, a votação foi em papel porque a urna não chegou a tempo, segundo o TRE do Distrito Federal.",
            "Para o 2º turno, a lição é a mesma do Brasil: quem tem eleitor inscrito e não votou tem margem a buscar. No exterior, esse eleitor está espalhado em {ext_cidades} cidades e depende de transporte e de agenda para votar.",
            "Há mais eleitor parado no exterior do que margem a disputar: {ext_ausentes} inscritos não votaram, contra uma diferença de {ext_margem} votos para Lula. Votar fora exige ir até um consulado, às vezes em outra cidade, e quem organiza isso ganha voto.",
        ],
    },
    {
        "tag": "A Câmara",
        "tom": "flavio",
        "titulo": "A direita ganhou {cam_ganho_direita} cadeiras. O bloco ainda não chega a três quintos.",
        "metrica": "{cam_bloco_d}",
        "metrica_rot": "de {cam_vagas} deputados são de direita ou centro-direita",
        "fig": A.fig_camara,
        "fonte": "TSE e alocação pelo quociente; camara.json e comparacao_2022.json",
        "texto": [
            "A Câmara eleita tem {cam_bloco_d} deputados de direita e centro-direita, {cam_bloco_e} de esquerda e centro-esquerda e {cam_centro} de centro, pela classificação de campo da casa. Em 2022 o bloco da direita tinha {cam_bloco_d_22}: andou {cam_delta_bloco_d}. A esquerda e a centro-esquerda andaram {cam_delta_bloco_e}. Só a direita, sem a centro-direita, ganhou {cam_ganho_direita} cadeiras e chegou a {cam_direita}.",
            "O número tem dois marcos. A maioria absoluta é de {cam_maioria} deputados, e o bloco passa dela com folga. Os três quintos de uma emenda constitucional são {cam_tres_quintos}, e o bloco fica abaixo. O PL terá {cam_pl} deputados, a maior bancada; o PT, {cam_pt}.",
            "Depois de PL e PT vêm União com {cam_uniao}, PSD com {cam_psd}, Republicanos e PP com {cam_rep} cada, e MDB com {cam_mdb}. É nesse meio que se decide votação apertada. O centro, com {cam_centro} cadeiras pela classificação da casa, fica menor do que em 2022 e perde o poder de veto que tinha sobre qualquer maioria.",
            "Votos e cadeiras andaram juntos. A direita teve {cam_votos_d} dos votos para a Câmara e ficou com {cam_cadeiras_d} das cadeiras; a esquerda teve {cam_votos_e} dos votos. O deputado mais votado do país foi {cam_top_nome}, com {cam_top_votos} de votos, {cam_top_pct} dos válidos de Minas Gerais.",
            "Na conversa, a tradução é simples. Quem votou num deputado de direita no domingo e ainda não decidiu o presidente já sabe com quem esse deputado vai querer governar. Não é argumento de propaganda; é argumento de mesa de cozinha, e funciona melhor do que qualquer vídeo.",
            "Juízo editorial, a favor de Flávio. Um presidente Flávio começa com maioria nas duas Casas sem depender do centro; a fidelidade de partidos como PP, União e Podemos a essa maioria é hipótese, não número. Um presidente Lula governaria contra {cam_bloco_d} deputados da direita e da centro-direita. Para o eleitor de centro que quer estabilidade, a composição já eleita é um argumento concreto.",
            "Juízo editorial, achado contrário. O mesmo número serve a Lula: o eleitor que teme concentração de poder pode votar nele como contrapeso. A campanha de Flávio não deve vender a maioria como cheque em branco; deve vendê-la como fim do impasse. Limite: em {cam_provisorias} a alocação ainda é provisória, feita pelo quociente, que reproduziu nome a nome as UFs que o TSE já fechou.",
        ],
    },
    {
        "tag": "O Senado",
        "tom": "flavio",
        "titulo": "O Senado de 2027 passa dos três quintos. E {sen_ufs_acima} nomes passaram Flávio.",
        "metrica": "{sen_bloco_d} de {sen_total}",
        "metrica_rot": "senadores de direita e centro-direita em 2027",
        "fig": A.fig_senado,
        "fonte": "TSE, eleitos de 2022 e de 2026; senado.json e senado_x_flavio.json",
        "texto": [
            "O Senado de 2027 soma os {sen_continuam} eleitos em 2022 e os {sen_novos} eleitos agora. Direita e centro-direita terão {sen_bloco_d} cadeiras, acima dos três quintos de {sen_tres_quintos}. Esquerda e centro-esquerda, {sen_bloco_e}; o centro, {sen_centro}. O PL terá {sen_pl} senadores, {sen_pl_2026} eleitos neste domingo; o PT, {sen_pt}.",
            "O PL fez as duas vagas em {sen_n_dobradinhas} UFs: {sen_dobradinhas}. Algumas disputas foram decididas no detalhe: a segunda vaga do {sen_apertada_uf} saiu por {sen_apertada_pp} ponto, {sen_apertada_votos} votos, e a do {sen_apertada2_uf} por {sen_apertada2_pp}. Um Senado com essa composição muda o que um presidente consegue aprovar, e também o que consegue barrar.",
            "O Senado também mede quem puxa voto. Cada eleitor vota em dois nomes, então a comparação justa é com a parcela dos eleitores que escolheu cada candidatura. Nessa régua, em {sen_ufs_acima} UFs uma candidatura do bloco aliado alcançou mais eleitores do que Flávio na mesma urna: {sen_acima_lista}.",
            "No agregado, as candidaturas do bloco aliado tiveram {sen_aliados_pct} da base de votos do Senado, contra {sen_flavio_pct} de Flávio nos válidos de presidente; são {sen_aliados_por_voto} votos de Senado do bloco para cada voto de Flávio. O PL sozinho ficou abaixo de Flávio em {sen_pl_ufs_abaixo} UFs: o partido do candidato não é o palanque mais forte dele em quase lugar nenhum.",
            "Leitura para o 2º turno. Os nomes que passaram Flávio estão concentrados no Nordeste e no Norte, onde ele perdeu. São senadores eleitos que conversam com um eleitor que vota na direita local e ainda não vota no presidenciável da direita. É o tipo de voto que nenhuma propaganda nacional alcança e que um palanque local pode alcançar.",
            "A pergunta prática é se esses senadores vão subir no palanque. Alguns já estão com Flávio; outros ainda não declararam. Cada um que subir leva junto um eleitorado que a urna já mostrou existir, e que nenhuma pesquisa nacional enxerga.",
            "Limite: mesma urna e cargos diferentes não dizem quem votou em quem. O vão é teto endereçável, nunca transferência certa. Parte de quem votou num senador aliado vota Lula por escolha, e alguns desses senadores ainda não declararam apoio.",
        ],
    },
    {
        "tag": "As assembleias",
        "tom": "flavio",
        "titulo": "Nas assembleias grandes, a direita tem maioria em {ass_maioria_n} de {ass_n}.",
        "metrica": "{ass_bloco_d}",
        "metrica_rot": "de {ass_vagas} deputados estaduais nas {ass_n} maiores casas",
        "fig": B.fig_assembleias,
        "fonte": "TSE; assembleias.json e comparacao_2022.json",
        "texto": [
            "Somadas as {ass_n} assembleias dos maiores colégios, direita e centro-direita elegeram {ass_bloco_d} dos {ass_vagas} deputados estaduais. Em 2022 eram {ass_bloco_d_22}. O bloco tem maioria sozinho em {ass_maioria_n} casas: {ass_maioria_lista}.",
            "São Paulo é o retrato mais nítido. A Assembleia tem {sp_vagas} cadeiras: direita {sp_d}, esquerda {sp_esq}, e o bloco da direita com a centro-direita soma {sp_bloco_d}. A direita sozinha ganhou {sp_delta_d} cadeiras. A deputada estadual mais votada do país foi {sp_top_nome}, do PL paulista, com {sp_top_votos} de votos.",
            "Minas Gerais tem {mg_vagas} cadeiras, com {mg_d} da direita e {mg_bloco_d} no bloco. A esquerda manda onde manda no voto presidencial: na Bahia tem {ba_esq} das {ba_vagas} cadeiras; no Ceará, {ce_esq} das {ce_vagas}. O mapa das assembleias é quase o mapa de 2026 em escala menor.",
            "Nas outras casas grandes, o bloco da direita fez {rj_bloco_d} de {rj_vagas} no Rio, {pr_bloco_d} de {pr_vagas} no Paraná, {sc_bloco_d} de {sc_vagas} em Santa Catarina, {go_bloco_d} de {go_vagas} em Goiás e {df_bloco_d} de {df_vagas} no Distrito Federal. No Rio Grande do Sul fica sem maioria própria, {rs_bloco_d} de {rs_vagas}, e o centro, com {rs_centro}, decide. Em Pernambuco, {pe_bloco_d} de {pe_vagas}. Em Minas, o deputado estadual mais votado foi {mg_top_nome}, do {mg_top_partido}, com {mg_top_votos} votos.",
            "Por que isso importa para o 2º turno? Deputado estadual é o político mais próximo do eleitor depois do vereador. Tem base em poucas cidades, conhece liderança de bairro, de igreja e de associação, e foi eleito há poucos dias com voto dessas pessoas. Quem venceu agora pela direita tem motivo e meio para pedir voto em Flávio nas próprias bases.",
            "Há também o argumento contrário, e ele vai aparecer. Assembleia de direita em estado grande muda a pauta local por quatro anos, e o eleitor de centro pode preferir equilíbrio em Brasília. É o mesmo raciocínio do contrapeso que vale para a Câmara. Deve ser respondido com proposta concreta, não com ataque.",
            "Juízo editorial. A campanha que quiser o voto de interior precisa desses deputados no chão, não só no palanque. Limite: a classificação de campo é editorial da casa, e a de São Paulo ainda é provisória, feita pelo quociente; a fidelidade de cada deputado a Flávio é hipótese, não número.",
        ],
    },
    {
        "tag": "Os governadores",
        "tom": "flavio",
        "titulo": "O vão estadual: onde o governador do lado de Flávio teve mais voto que ele.",
        "metrica": "{vao_sp}",
        "metrica_rot": "pontos de Tarcísio sobre Flávio em São Paulo",
        "fig": B.fig_governadores,
        "fonte": "TSE, governador e presidente na mesma urna; governadores.json",
        "texto": [
            "Foram {gov_1t} governadores eleitos no 1º turno: {gov_d} de direita, {gov_cd} de centro-direita, {gov_c} de centro e {gov_e} do PT. Há 2º turno em {gov_2t} UFs: {gov_2t_lista}.",
            "O vão estadual compara, na mesma urna, o governador com o presidenciável do mesmo lado. Em São Paulo, Tarcísio fez {sp_tarc} e Flávio {sp_flavio}: {vao_sp} pontos. Em Alagoas, JHC ficou {vao_al} pontos acima. Em Mato Grosso do Sul, {vao_ms}; em Minas, Cleitinho, {vao_mg}; no Pará, {vao_pa}. Do lado de Flávio, o governador teve parcela maior em {vao_pos} UFs e menor em {vao_neg}.",
            "Há vãos grandes que não são aliança. Na Paraíba, Lucas Ribeiro teve {vao_pb_flavio} pontos sobre Flávio, mas é de um governo aliado de Lula. No Maranhão e em Pernambuco, Eduardo Braide e Raquel Lyra ficaram {vao_ma} e {vao_pe} pontos acima de Flávio e não declararam apoio a ele. Ali o vão é teto, não palanque.",
            "E há o sinal contrário, que precisa sair com o mesmo destaque. Moro, no Paraná, ficou {vao_pr} pontos abaixo de Flávio; Marcos Rogério, em Rondônia, {vao_ro}; Mailza, no Acre, {vao_ac}. Do lado de Lula, os governadores do PT também ficaram abaixo do presidenciável: Elmano no Ceará, {vao_ce}; Jerônimo na Bahia, {vao_ba}; Cadu de Lula no Rio Grande do Norte, {cadu}. Onde o governador tem menos voto que o presidenciável, ele é palanque, não reserva.",
            "Juízo editorial: os 2º turnos estaduais são palanque pronto. No Rio, Douglas Ruas teve {rj_ruas} contra {rj_paes} de Eduardo Paes, aliado de Lula. No Distrito Federal, Celina Leão ficou com {df_celina}; no Espírito Santo, Lorenzo Pazolini com {es_pazolini}; no Tocantins, Professora Dorinha com {to_dorinha}. Moro venceu no Paraná com {pr_moro}, no limite. Casar a campanha do governador com a do presidente nessas UFs é a forma mais barata de levar o eleitor de volta à urna.",
            "Onde não há 2º turno estadual, o governador eleito tem menos motivo para fazer campanha agora. Pedir a ele um dia de rua com Flávio custa pouco e rende justamente onde o vão é positivo.",
            "Rótulo obrigatório: o vão é teto endereçável, nunca transferência certa. Mesma urna, cargos diferentes. Parte do eleitor de Tarcísio vota Lula por escolha, e isso foi medido em pesquisa antes do 1º turno. O que o vão diz é onde vale a pena levar o governador para a rua com Flávio.",
        ],
    },
    {
        "tag": "Pesquisas contra urna",
        "tom": "lula",
        "titulo": "As pesquisas erraram para o mesmo lado de 2022.",
        "metrica": "{erro_comum}",
        "metrica_rot": "pontos de erro comum na diferença, a favor de Lula",
        "fig": B.fig_pesquisas,
        "fonte": "Última onda de {n_casas} institutos; pesquisas_vs_urna.json",
        "texto": [
            "A média das últimas ondas de {n_casas} institutos dava Lula {pesq_dif} pontos à frente nos válidos. A urna deu Flávio {dif_pp} à frente. O erro comum na diferença foi de {erro_comum} pontos a favor de Lula, com mediana de {erro_mediana}. Em 2022, a mesma conta tinha dado {erro_2022}. Duas eleições, o mesmo lado. {casas_lula} das {n_casas} casas superestimaram Lula, e {casas_fora} erraram além da própria margem.",
            "Os mais próximos da urna foram {prox1} e {prox2}, com erro de {prox_erro}. Proximidade numa eleição não é acerto: com a dispersão observada, a chance de ao menos uma casa cair a meio ponto da urna só por acaso era de {prob_meio_ponto}. É uma observação, não uma prova de método.",
            "O modo de coleta pesa. As {pres_n} casas presenciais erraram em média {pres_media} pontos; as {tel_n} por telefone, {tel_media}; as {onl_n} online, {onl_media}. E o efeito de casa medido antes da eleição, que ordena os institutos entre si, tem correlação de {corr_casa} com o erro final: quem já puxava para Lula antes da urna foi quem mais errou.",
            "A estrela da casa, a reponderação por renda pela régua da PNAD, passou no teste. No agregador, o erro foi de {agr_pub} pontos para {agr_rep} depois de trocar a renda declarada pela do IBGE. Das {rep_n} últimas ondas que permitiam a conta, {rep_aprox} andaram para perto da urna.",
            "O que esperar das pesquisas de 2º turno: se o padrão se repetir, elas vão subestimar Flávio de novo. A casa não corrige pesquisa pelo erro passado; publica a medição e o erro histórico lado a lado, como cenário nas duas direções.",
            "A central da casa, publicada na véspera, dava Flávio {central_f} e Lula {central_l} nos válidos: erro de {central_erro} na diferença, menor que o de {central_melhor_que} dos {n_casas} institutos. Ela dava {central_p} de chance de Flávio na frente: empate técnico, nunca aposta. A urna caiu no percentil {central_percentil} da simulação. No Senado, a nota de Brier foi {sen_brier}, contra {sen_brier_uniforme} de quem chutasse ao acaso, e os dois mais prováveis levaram {sen_acertos} das {sen_vagas} vagas. Nos governos, a casa acertou o líder em {gov_acertos} UFs e esperava {gov_esperado} decisões no 1º turno; vieram {gov_decididos}.",
            "Limite: nada disso prova intenção de instituto. Prova que o erro tem lado e se repete, e que a régua de renda corrige parte dele. Para o 2º turno, a regra da casa continua: manchete que diz que alguém lidera precisa passar na margem da diferença e na troca da renda pela PNAD.",
        ],
    },
    {
        "tag": "O voto útil",
        "tom": "outros",
        "titulo": "O voto útil explica quatro décimos do erro. O resto foi movimento.",
        "metrica": "{vu_explica}",
        "metrica_rot": "do erro das pesquisas explicado pela consolidação",
        "fig": B.fig_voto_util,
        "fonte": "Média das últimas ondas e urna; voto_util.json",
        "texto": [
            "As pesquisas finais davam {vu_pesq} dos válidos à terceira via. A urna deu {vu_urna}. Renan Santos perdeu {vu_renan} pontos entre a média das pesquisas e a urna; Caiado, {vu_caiado}; Cury, {vu_cury}; Zema, {vu_zema}. Flávio ganhou {vu_f_ganho} pontos sobre a média das pesquisas, e Lula, {vu_l_ganho}.",
            "Em proporção, Zema perdeu {rel_zema} do que tinha nas pesquisas; Renan, {rel_renan}; Caiado, {rel_caiado}; Cury, só {rel_cury}. Renan e Caiado, juntos, respondem por {fat_renan} e {fat_caiado} de toda a queda da terceira via. O eleitor de Cury foi o que mais ficou onde estava, e é por isso que ele é o maior bloco a disputar no 2º turno.",
            "Medimos o que os próprios institutos tinham publicado: quanto cada finalista subia do 1º para o 2º turno na mesma amostra. É a reserva de 2º turno. A urna revelou, já no 1º turno, {vu_reserva_f} da reserva de Flávio, na mediana das casas, e {vu_reserva_l} da de Lula. O voto útil foi quase todo para um lado.",
            "Quanto disso explica o erro das pesquisas? Aplicando a matriz de transferência da Nexus ao que a terceira via perdeu, a consolidação responde por {vu_explica_pp} dos {erro_comum} pontos de erro na diferença: {vu_explica}. Com outras hipóteses para a matriz, a fatia vai de {vu_faixa_min} a {vu_faixa_max}. O resto é deslocamento entre os finalistas que os dados agregados não separam: efeito de casa, movimento tardio, comparecimento diferente do previsto.",
            "A lição para o 2º turno é direta. O eleitor de terceira via já mostrou que se move, e se move para Flávio quando entende que o voto dele decide. Renan perdeu mais da metade do que tinha nas pesquisas para a urna sem que ninguém precisasse convencer esse eleitor de nada. A conversa do 2º turno começa com quem já está a meio caminho.",
            "Há o achado contrário. A reserva de Lula, o quanto ele subia do 1º para o 2º turno nas pesquisas, ficou quase toda guardada: a urna revelou só {vu_reserva_l} dela. Esse voto ainda existe e vai aparecer no 2º turno. A campanha de Flávio não pode fazer a conta como se a reserva de Lula tivesse evaporado.",
            "Limite: a decomposição usa médias de pesquisas, não eleitores identificados. A matriz da Nexus é de setembro e nacional. O número certo é uma faixa, e a faixa é larga.",
        ],
    },
]
