"""Posts 13 a 24 da super thread: auditoria por zona e por seção, limites,
checklist e os quatro posts do 2º turno."""

from __future__ import annotations

from . import thread_fig_b as B
from . import thread_fig_c as C

LIMITES = [
    (
        "Verificado",
        "#1457aa",
        [
            "Flávio à frente em todas as versões do arquivo nacional",
            "Três paradas do arquivo nacional no pico",
            "Meia hora sem arquivo de resultado de cargo nenhum",
            "Erro das pesquisas a favor de Lula",
        ],
    ),
    (
        "Inferência",
        "#0f7f5f",
        [
            "Queda da vantagem pela ordem de chegada",
            "Volume pequeno para um banco atual",
            "Seções extremas em enclaves que já votavam assim",
            "Modelo de urna: alocação, não máquina",
        ],
    ),
    (
        "Hipótese",
        "#7d5b00",
        [
            "Gargalo no banco da totalização",
            "Política local nas zonas atípicas a checar",
            "Fila e mesário nas seções que fecham tarde",
            "Matriz nacional aplicada a cada cidade",
        ],
    ),
    (
        "Não provado",
        "#b02f21",
        [
            "Fraude em qualquer nível",
            "A causa da pausa geral",
            "Quem trocou de voto entre 2022 e 2026",
            "O resultado do 2º turno",
        ],
    ),
]


def etapas_checklist(v: dict) -> list[tuple[str, str, str]]:
    return [
        (
            "Baixe o arquivo nacional final do TSE",
            v["fo_sha"],
            "e confira a impressão digital SHA-256",
        ),
        (
            "Some os arquivos das UFs",
            v["div_secoes"],
            "seções de diferença no pior minuto da noite",
        ),
        (
            "Abra os boletins de urna seção a seção",
            v["fo_boletins"],
            f"boletins entre {v['fo_cadastro']} seções do cadastro",
        ),
        (
            "Compare com 2022 nos arquivos do próprio TSE",
            v["mun_total"],
            "municípios com os dois anos completos",
        ),
        (
            "Rode os scripts do dossiê",
            v["fo_versoes"],
            "versões de arquivo guardadas pelo coletor",
        ),
    ]


POSTS_B: list[dict] = [
    {
        "tag": "Anomalias por zona",
        "tom": "outros",
        "titulo": "As {an_topo} zonas mais estranhas do país. Nenhuma aponta para fraude.",
        "metrica": "{an_comum} de {an_topo}",
        "metrica_rot": "têm explicação comum; {an_hip} pedem checagem local",
        "fig": B.fig_anomalias,
        "fonte": "Quatro modelos de anomalia sobre {an_zonas} zonas; anomalias.json",
        "texto": [
            "Procuramos o estranho de propósito. Cada uma das {an_zonas} zonas eleitorais recebeu um escore de atipicidade feito por quatro métodos independentes: escore robusto dentro da UF, distância de Mahalanobis robusta, Isolation Forest e LOF. As variáveis: quanto Flávio e Lula andaram contra 2022, o resíduo da zona depois de tirar a UF e a vizinhança, comparecimento, brancos e nulos, terceira via, crescimento do eleitorado e a hora em que a zona fechou.",
            "Das {an_topo} mais atípicas, {an_comum} têm explicação comum. Zona pequena, onde poucos votos mexem muito. Eleitorado que cresceu {an_tib_eleit} desde 2022, como em Tibau, no Rio Grande do Norte, por transferência de título. Caiado com {an_gg_caiado} em Guarani de Goiás. Cury com {an_col_cury} em Colina, a cidade natal dele. E padrão regional, quando as zonas vizinhas também estão no topo.",
            "Um cuidado de método evitou alarme falso: {an_locais} zonas redesenhadas desde 2022 receberam a base de comparação pelo local de votação, e a hora de fechamento foi corrigida para o fuso de cada lugar. Sem isso, o Acre e o oeste do Amazonas pareceriam atrasados em até duas horas, e zonas novas pareceriam ter mudado de voto do nada.",
            "As outras {an_hip} ficam como hipótese de política local, a checar seção a seção: prefeito forte, candidatura estadual da região, liderança. Em Queimada Nova, no Piauí, brancos e nulos chegaram a {an_qn_bn} dos votos. Nenhuma das {an_topo} tem o desenho que a fraude deixaria: urna isolada fora do padrão do próprio lugar sem nenhuma outra explicação. A lista é estável: com outra semente do Isolation Forest, {an_rob} das {an_rob_n} continuam no topo.",
            "Testamos também as zonas que fecharam muito depois da própria UF. São {an_tard_n}. Nelas a margem andou {an_tard_swing} pontos para Flávio, contra {an_dem_swing} nas demais, mas a UF explica quase tudo: o andamento médio das UFs dessas zonas foi de {an_tard_uf}. Depois de descontar UF e vizinhança, o resíduo médio é {an_tard_res} nas tardias e {an_dem_res} nas demais. Atraso não move voto.",
            "O que fecharia cada caso é documento: ata da mesa, registro da urna e boletim de ocorrência, se houver. A lista completa, com o motivo de cada zona, está no dossiê. Quem tiver informação local sobre alguma delas pode conferir com o próprio olho.",
        ],
    },
    {
        "tag": "Seções de {lim90}",
        "tom": "lula",
        "titulo": "As seções de {lim90} de Lula são enclaves que já votavam assim em 2022.",
        "metrica": "{s_ja90} de {s_casadas}",
        "metrica_rot": "seções de {lim90} de Lula que já davam {lim90} a ele em 2022",
        "fig": B.fig_secoes90,
        "fonte": "{s_base} boletins de urna de 2026 e votação por seção de 2022; secoes.json",
        "texto": [
            "Abrimos os {s_base} boletins de urna, seção por seção. Em {s90_l} seções Lula teve {lim90} ou mais dos válidos, {s90_l_pct} do total, com {s90_l_aptos} eleitores aptos. Flávio passou de {lim90} em {s90_f}. Com {lim100} dos válidos para um só nome, são {s100_l} seções de Lula e {s100_f} de Flávio. O número chama atenção nas redes. O dado explica.",
            "Primeiro, o lugar. Essas seções estão em zonas que já votam muito em Lula: a mediana do resto da zona é de {s_zona_med} para ele. A seção de {lim90} fica, tipicamente, {s_excesso} pontos acima da própria zona. Em locais com nome de aldeia ou escola indígena, {s_ald_90} das {s_ald_todas} seções deram {lim90} ou mais a Lula, {s_ald_pct} do tipo. Em zona rural, {s_rural_90}.",
            "Por UF, o {uf90} é onde essas seções mais pesam: {uf90_n} seções de {lim90} de Lula, {uf90_pct} das seções do estado. São comunidades indígenas e ribeirinhas que votam em bloco há muitas eleições.",
            "Segundo, a história. Casamos com 2022 as seções que mantiveram número e local. Das {s_casadas} seções de {lim90} de Lula que existem nos dois anos, {s_ja90} já davam {lim90} ou mais a ele no 1º turno de 2022, e {s_ja80} davam {lim80} ou mais. A mediana de 2022 nessas seções foi de {s_med22}. Não surgiu nada novo: são enclaves que votam assim há pelo menos duas eleições.",
            "Do lado de Flávio, o desenho é outro e merece o mesmo destaque. Das {f90_casadas} seções de {lim90} dele que existem nos dois anos, só {f90_ja} já davam {lim90} a Bolsonaro no 1º turno de 2022; a mediana era {f90_med22}, e subiu {f90_var} pontos. Os enclaves de Flávio são mais novos e menores. Acima de {lim95}, são {s95_l} seções de Lula e {s95_f} de Flávio.",
            "Terceiro, os sinais clássicos de manipulação não aparecem. Seções com comparecimento acima de {lim100} dos aptos: {comp_acima_100}. Com exatamente {lim100}: {comp_igual_100}, quase todas minúsculas. Seções com {zero_min_votantes} votantes ou mais e nenhum voto em Lula: {zero_lula}. Nenhum voto em Flávio: {zero_flavio}, das quais {zero_flavio_am} no Amazonas, em comunidades remotas.",
            "O que não sabemos: por que cada enclave vota assim. Lealdade histórica, liderança comunitária, pressão local ou compra de voto são hipóteses diferentes, e o boletim não separa uma da outra. O que os separaria é documento: ata da mesa, fiscais presentes e registro da urna. Nas seções de maior peso, vale ter fiscal no 2º turno.",
        ],
    },
    {
        "tag": "Os grupos de seções",
        "tom": "outros",
        "titulo": "Pedimos grupos ao algoritmo duas vezes. Sobrou o que o mapa já mostra.",
        "metrica": "{cl_v}",
        "metrica_rot": "V de Cramér entre grupo e região com cinco partes; antes, {cl_v15}",
        "fig": B.fig_grupos,
        "fonte": "Mistura gaussiana com k = {cl_k} sobre o boletim de cada seção; secoes.json",
        "texto": [
            "Uma técnica comum de auditoria é pedir a um algoritmo que agrupe as seções pelo perfil de voto e procurar o grupo que foge do esperado. Fizemos isso duas vezes, com uma mistura gaussiana de {cl_k_ext} grupos sobre o boletim de cada seção. A segunda tentativa só existe porque a primeira não deu certo.",
            "A primeira usou {cl_n15} partes: as doze candidaturas, brancos, nulos e abstenção. {cl_zeros15} das células eram zero, porque a maioria das seções não dá voto nenhum às nanicas, e o método troca o zero por um número minúsculo antes do logaritmo. O salto do zero para um voto vira uma distância de {cl_deg15} unidades, e o algoritmo agrupou as seções por quem tem ou não tem voto em {cl_nuvem1}, em {cl_nuvem2} e nas nanicas. A associação entre grupo e região ficou em {cl_v15}, perto de nenhuma.",
            "Refizemos com as cinco partes que interessam: Lula, Flávio, brancos, nulos e abstenção. O voto nos outros dez candidatos fica fora e aparece no gráfico como o que falta para fechar o eleitorado. Os zeros caíram para {cl_zeros} das células.",
            "Não bastou. Brancos e nulos são poucos votos por seção, com mediana de {cl_med_brancos} brancos e {cl_med_nulos} nulos. {cl_art_n} dos cinco grupos ainda são artefatos da contagem: {cl_art_lista}. No logaritmo, zero vira degrau e empate vira razão exata, e o algoritmo encaixa um grupo em cada padrão.",
            "Os outros {cl_perfis_n}, com {cl_perfis_pct} das seções, são perfis de voto de fato. Num, Lula tem {cl_lula_lula} dos válidos e Flávio {cl_lula_flavio}, com {cl_lula_reg_pct} das seções no {cl_lula_reg}. No outro, Flávio tem {cl_flavio_flavio} e Lula {cl_flavio_lula}, com {cl_flavio_reg_pct} no {cl_flavio_reg}. É a divisão que o mapa por zona já mostra; nessa parte, o algoritmo não acrescenta nada.",
            "Por que as partes pequenas mandam: no logaritmo, passar de {cl_med_brancos} para {cl_dobro_brancos} brancos afasta a seção tanto quanto passar de {cl_med_lula} para {cl_dobro_lula} votos em Lula. Com zero trocado por meio voto, a associação com a região sobe para {cl_v_mv}. E o ajuste não é estável: das {cl_partidas} partidas do algoritmo, só {cl_nomax} chegaram ao melhor resultado, e as outras dividem as seções de outro jeito.",
            "Lição de método: algoritmo de agrupamento acha estrutura sempre, e a pergunta é o que separa os grupos. Aqui, primeiro zero voto em nanica, depois zero e empate em brancos e nulos, e por fim a divisão regional. Nenhum grupo aponta irregularidade.",
        ],
    },
    {
        "tag": "O modelo de urna",
        "tom": "outros",
        "titulo": "Urna nova contra urna velha: menos de um ponto, e o sinal muda.",
        "metrica": "{urna_max}",
        "metrica_rot": "pontos, o maior efeito em módulo entre as quatro réguas",
        "fig": B.fig_urna,
        "fonte": "Modelo de urna de cada boletim, 2022 e 2026; secoes.json",
        "texto": [
            "A pergunta circulou na noite: a urna mais nova vota diferente da mais velha? O boletim de cada seção diz qual modelo foi usado, e isso permite medir. Mas a comparação ingênua engana, porque os modelos não são distribuídos ao acaso: o TRE escolhe onde vai cada um. Por isso usamos quatro réguas, cada uma controlando uma coisa diferente.",
            "Dentro da mesma zona, a urna mais nova dá a Flávio {uz_est} ponto em relação à mais velha, com intervalo de {uz_lo} a {uz_hi}, em {uz_n} zonas. No mesmo prédio, {ul_est}, de {ul_lo} a {ul_hi}, em {ul_n} locais. Com a linha de base da própria seção em 2022, {uv_est}, de {uv_lo} a {uv_hi}, em {uv_n} zonas. E nas mesmas seções que trocaram de urna velha para nova entre 2022 e 2026, {ut_est}, de {ut_lo} a {ut_hi}, em {ut_n} zonas.",
            "As quatro ficam abaixo de um ponto, e o sinal muda conforme o controle: duas a favor de Flávio, duas contra. Um efeito da máquina apareceria com o mesmo sinal nas réguas que controlam o lugar, porque a máquina é a mesma onde quer que esteja. O que muda de sinal com o controle é a alocação: quem recebeu urna nova dentro de cada zona.",
            "Leitura: não há efeito do equipamento detectável. Há diferença de lugar, e o documento que a resolve é o plano de alocação de urnas de cada TRE, que diz por que uma seção recebeu um modelo e não outro. É um documento público e deveria vir junto com o resultado.",
            "Em 2022 a mesma régua, dentro da zona, deu ao modelo mais novo daquela eleição {u22_est} ponto a Bolsonaro, intervalo de {u22_lo} a {u22_hi}, em {u22_n} zonas. Se a máquina favorecesse alguém, seria o candidato da direita em 2022 e da esquerda em 2026 dentro da zona. Não faz sentido; alocação faz.",
            "A régua bruta, sem controle nenhum, é a que engana. Ela dá {uz_bruto} ponto dentro de cada par de modelos, quase o dobro da régua dentro da zona, porque urna nova vai mais para cidade grande e cidade grande vota diferente do interior. Quem publicar a diferença bruta como efeito da máquina está medindo geografia.",
            "Limite: intervalo de confiança mede incerteza de amostra, não viés de alocação. As réguas de 2022 dependem do casamento de seções pelo número e pelo local, que perde parte delas. Nada aqui substitui a auditoria do código e dos equipamentos que o TSE já faz com partidos e instituições.",
        ],
    },
    {
        "tag": "Fechamento tardio",
        "tom": "lula",
        "titulo": "A seção que fecha tarde vota mais em Lula. Já votava em 2022.",
        "metrica": "{fe_inc_ctrl}",
        "metrica_rot": "pontos de Lula por hora de atraso, dentro da zona e com controles",
        "fig": C.fig_fechamento,
        "fonte": "Hora do último voto de cada boletim, 2022 e 2026; fechamento.json",
        "texto": [
            "Cada boletim de urna grava a hora do último voto. Na hora de encerrar, quem está na fila recebe senha e vota depois, e algumas seções votam até a noite. Sem controle nenhum, Lula teve {fe_b0} dos válidos nas seções que fecharam de {fe_f0}, {fe_b1} de {fe_f1}, {fe_b2} de {fe_f2} e {fe_b3} {fe_f3}. A correlação é forte e fácil de usar mal.",
            "Com controles, ela encolhe. Sem controle, cada hora de atraso vem com {fe_inc_bruta} pontos de Lula. Dentro da mesma zona, {fe_inc_zona}. Dentro da zona, com tamanho da seção e tipo de local, {fe_inc_ctrl}, intervalo de {fe_inc_ctrl_lo} a {fe_inc_ctrl_hi}. Sobra {fe_sobra} da correlação bruta. E o padrão não nasceu agora: a seção que chega tarde ao TSE vota mais em Lula do que a própria zona em {fe_dec22} pontos em 2022 e {fe_dec26} em 2026.",
            "O atraso é, antes de tudo, tamanho e distância. Com quatrocentos eleitores ou mais, {fe_tam_grande} das seções fecharam às {h18} ou depois; com menos de duzentos, {fe_tam_pequena}. Há {fe_mun_persist} municípios no décimo mais tardio do país nos dois anos, {fe_mun_razao} vezes o esperado por acaso, e {fe_locais} locais de votação que atrasam sempre, {fe_locais_rural} deles em zona rural, assentamento ou quilombo, contra {fe_locais_rural_base} no conjunto.",
            "Por UF, as que mais fecharam às {h18} ou depois foram {fe_uf1}, com {fe_uf1_pct} das seções, {fe_uf2}, com {fe_uf2_pct}, e {fe_uf3}, com {fe_uf3_pct}. Na outra ponta, {fe_ufz}, com {fe_ufz_pct}. O mapa do atraso é o mapa da distância e da seção grande, e coincide com o mapa do voto em Lula. Daí a correlação bruta.",
            "O que sobra dentro da zona existe e é positivo para Lula. O boletim não diz por quê. Fila, identificação lenta, mesário que vota no lugar de ausente e boca de urna são hipóteses diferentes, e só a ata da mesa e o registro da urna, com cada habilitação e sua hora, separam uma da outra. Hipótese não é achado.",
            "Para o 2º turno, a mesma ordem vale: essas seções vão chegar por último ao TSE, com voto mais lulista, e vão encurtar a vantagem de quem lidera cedo. É esperado e não é sinal de nada.",
            "Juízo editorial. A providência barata é pôr fiscal de partido nas seções que historicamente fecham tarde, onde a fila depois do horário e a mesa ficam sem testemunha. A lei permite que um mesmo fiscal cubra mais de uma seção do mesmo local, e os {fe_locais} locais persistentes somam {fe_locais_secoes} seções.",
        ],
    },
    {
        "tag": "A lentidão",
        "tom": "flavio",
        "titulo": "Com as paradas e tudo, 2026 foi mais rápido que 2022 em todas as UFs.",
        "metrica": "{le_rapidas} de {le_ufs}",
        "metrica_rot": "UFs que passaram de {m99} das seções mais cedo que em 2022",
        "fig": C.fig_lentidao,
        "fonte": "Arquivos de UF de 2026 e detalhe por seção de 2022 do TSE; lentidao_ufs.json",
        "texto": [
            "Uma pergunta justa depois das paradas: a apuração de 2026 foi lenta? Comparamos com 2022, UF por UF, pela hora em que cada uma passou de {m50}, {m90} e {m99} das seções totalizadas. No marco de {m99}, {le_rapidas} das {le_ufs} UFs chegaram mais cedo em 2026. O país passou de {m50} às {le_50_26}, contra {le_50_22} em 2022; de {m90} às {le_90_26}, contra {le_90_22}; de {m99} às {le_99_26}, contra {le_99_22}.",
            "O recebimento dos boletins também andou mais rápido. A mediana de chegada ao TSE foi às {le_rec26}, contra {le_rec22} em 2022, e depois das {h19} chegaram {le_rec26_19} das seções, contra {le_rec22_19} quatro anos antes. A contagem chegou mais cedo. O que travou foi a publicação.",
            "A cauda também encurtou. Em 2022, a última seção do país só entrou no arquivo às {le_100_22}, contando os dias depois da eleição. Em 2026, às {le_100_26}. As últimas seções são sempre as mesmas: aldeias, comunidades ribeirinhas e municípios onde a mídia da urna viaja de barco ou de avião até o ponto de transmissão.",
            "O Distrito Federal, primeiro a fechar nos dois anos, chegou a todas as seções às {df_100_26} em 2026, contra {df_100_22} em 2022. A melhora é geral, das UFs mais rápidas às mais lentas.",
            "A ordem das UFs quase não muda de um ano para o outro: a correlação de postos entre 2022 e 2026 é de {le_spearman}. As lentas são lentas sempre. Há {le_n_lentas} UFs no grupo das mais lentas nos dois anos: {le_lentas}. São estados grandes, de interior extenso, com seções em lugares onde a mídia da urna viaja horas até o ponto de transmissão.",
            "Por isso a frase certa sobre a noite é mais precisa que as duas versões que circularam. Não é verdade que a apuração de 2026 foi lenta; ela foi mais rápida que a de 2022. Também não é verdade que tudo correu normalmente: o painel nacional parou no pico e houve meia hora sem arquivo de resultado de cargo nenhum. As duas coisas são verdadeiras ao mesmo tempo.",
            "Para o 2º turno, a previsão razoável é a mesma ordem de chegada: Sul e Centro-Oeste primeiro, Nordeste e Norte no fim. A vantagem de quem lidera nas primeiras horas vai cair outra vez. Quem souber disso antes não vai se assustar nem comemorar cedo.",
        ],
    },
    {
        "tag": "Os limites",
        "tom": "lula",
        "titulo": "O que os dados provam, o que inferem e o que não provam.",
        "metrica": "{f_vs_b2t}",
        "metrica_rot": "pontos que Flávio ainda está abaixo de Bolsonaro no 2º turno de 2022",
        "fig": lambda: C.fig_limites(LIMITES),
        "fonte": "Classificação do dossiê: verificado, inferência, hipótese, juízo editorial",
        "texto": [
            "Uma auditoria séria publica o que contraria a própria tese com o mesmo destaque. Aqui vai a lista. Primeiro, o achado contrário mais importante: Flávio ainda está {f_vs_b2t} pontos abaixo de Bolsonaro no 2º turno de 2022, e o estoque de eleitores de 2022 que Lula pode recuperar é {estoque_razao} vezes o de Flávio: {estoque_l} contra {estoque_f}. Quem tem mais voto antigo para buscar é Lula.",
            "Segundo, a seção que fecha tarde vota mais em Lula mesmo com controles, {fe_inc_ctrl} pontos por hora dentro da zona. Isso não prova irregularidade, mas também não some. Terceiro, {an_hip} zonas atípicas continuam sem explicação estrutural e pedem checagem local. Quarto, a causa da pausa geral do TSE não está nos dados públicos; o carimbo de recebimento pode ser aplicado por uma peça posterior à recepção.",
            "O que os dados não provam: fraude, em nenhum nível. Nenhum teste que fizemos, por zona, por seção, por modelo de urna ou por hora, mostrou o desenho que a fraude deixaria. Também não provam quem trocou de voto entre 2022 e 2026, porque saldo agregado não identifica eleitor. E não provam o resultado do 2º turno.",
            "O que é hipótese declarada: o gargalo no banco da totalização; a política local nas zonas atípicas; fila e mesário nas seções tardias; e, no 2º turno, a matriz nacional de transferência aplicada a cada cidade, como se o eleitor de Cury em Salvador votasse igual ao de Cury em Joinville. As matrizes são de setembro, de institutos que erraram a diferença em {erro_comum} pontos.",
            "A classificação de campo também é escolha declarada da casa, não fato da natureza. Tucano conta como centro-esquerda; PP, União e Podemos como centro-direita; PSD e MDB como centro, com exceções por candidatura escritas no código. Quem classificar diferente vai chegar a blocos um pouco diferentes, e o dossiê mostra os números por partido para isso.",
            "Na Câmara, a alocação em {cam_provisorias} ainda é provisória. A régua de 2022 é uma eleição só, com outra terceira via. Tudo isso está no dossiê com o rótulo certo. Quem quiser derrubar uma conclusão encontra lá o caminho para tentar.",
        ],
    },
    {
        "tag": "Confira você mesmo",
        "tom": "flavio",
        "titulo": "Cinco passos para conferir qualquer número desta thread.",
        "metrica": "{fo_versoes}",
        "metrica_rot": "versões de arquivos do TSE guardadas durante a noite",
        "fig": None,
        "fonte": "Arquivos públicos do TSE; scripts e dados do dossiê em brasil.arvor.co",
        "texto": [
            "Nada nesta thread pede confiança. Pede conferência. O coletor da casa leu os arquivos públicos do TSE a noite inteira e guardou {fo_versoes} versões, cada uma com a hora em que o tribunal a gerou, a hora em que foi lida e a impressão digital SHA-256. O arquivo nacional de presidente teve {fo_nacional} versões; a final começa com a impressão {fo_sha}.",
            "Primeiro passo: baixe do TSE o arquivo nacional final e confira a impressão digital. Segundo: some os arquivos das UFs e compare com o nacional ao longo da noite; no pior minuto, às {div_hora}, a diferença foi de {div_secoes} seções. Terceiro: abra os boletins de urna seção a seção. São {fo_boletins} boletins entre {fo_cadastro} seções do cadastro, porque seções agregadas votam no boletim da principal.",
            "Quarto: compare com 2022 nos arquivos do próprio TSE, município a município. São {mun_total} municípios com os dois anos completos. Quinto: rode os scripts do dossiê. Cada capítulo tem um script que lê o banco e grava um arquivo de dados; a página e esta thread só leem esses arquivos. Se um número estiver errado, o erro está num lugar que você pode apontar.",
            "Também publicamos o que ficou de fora e por quê. {fo_zona_div} seções em três zonas foram excluídas da análise seção a seção porque o TSE não publicou o boletim de algumas seções que o arquivo da zona conta como totalizadas; {fo_sem_bu} seções principais não têm boletim. O contexto da noite tem {fo_contexto} itens, entre documento oficial, imprensa e relato, cada um com o degrau de evidência.",
            "O que não fazer com esta thread: não recorte um card sem o rótulo, não troque inferência por verificado e não use a queda da vantagem durante a noite como prova de nada. Print de painel sem hora de geração não serve para auditoria; o arquivo do TSE tem a hora impressa e a impressão digital, e é ele que vale.",
            "Checklist do leitor para qualquer auditoria, nossa ou dos outros: de onde veio o número; quem gerou o arquivo e quando; se dá para refazer a conta; o que ficou de fora; o que contraria a tese; e se o texto diz quando é opinião. Se uma auditoria não passa nessas seis perguntas, não compartilhe.",
        ],
    },
    {
        "tag": "2º turno: a conta",
        "tom": "flavio",
        "titulo": "A conta favorece Flávio. O perigo está em casa.",
        "metrica": "{eq_lula_todos}",
        "metrica_rot": "de toda a terceira via que Lula precisaria para virar",
        "fig": C.fig_aritmetica,
        "fonte": "Urna do 1º turno e matriz Nexus/BTG de setembro; estrategia_2t.json",
        "texto": [
            "Flávio sai do 1º turno com {dif_mi} de votos de vantagem. A terceira via teve {terc_mi}. Para virar só com esses votos, Lula precisaria de {eq_lula_todos} de todos eles, se todos votassem. Entre os que escolhem um dos dois, precisaria de {eq_lula_escolhe}. A matriz de transferência da Nexus, a única com uma linha para cada candidatura, mede {eq_lula_medido}.",
            "Aplicada a matriz, só com o que foi medido, Flávio vai a {nx_f} dos válidos contra {nx_l}, margem de {nx_margem} de votos. Nas seis combinações de matriz e hipótese que testamos, a margem vai de {margem_min} a {margem_max}. Mesmo que toda a não escolha da terceira via, {eq_nao_escolha} de votos, fosse para Lula, Flávio ainda teria {eq_sobra} de vantagem. Se cada voto de terceira via rendesse o que rendeu entre os turnos de 2022, Flávio teria {an22_f}.",
            "Onde está o risco, então? Na base e no comparecimento. A margem central some se {eq_base_troca} dos eleitores de Flávio no 1º turno votarem em Lula, ou se {eq_base_abst} deles ficarem em casa. E Lula tem mais eleitor antigo para buscar: o estoque de 2022 que ele pode recuperar soma {estoque_l}, contra {estoque_f} de Flávio. O caminho de Lula é trazer quem faltou; foram {abst_1t} de ausentes.",
            "Juízo editorial: a campanha de Flávio é de defesa. Primeiro movimento, não deixe nenhum voto em casa. Comece pela própria rede: pais, avós, tios, vizinhos, igreja, trabalho. Pergunte se votaram no dia do 1º turno. Se não votaram, pergunte por quê. Quem acha que já está ganho é o eleitor mais perigoso do Flávio.",
            "Onde está esse voto em casa? Contra o 1º turno de 2022, o comparecimento caiu {comp_cs} ponto no Centro-Sul, onde Flávio é mais forte, e subiu {comp_ne} no Nordeste. É a direção errada para ele. Trazer o eleitor do Centro-Sul de volta vale mais do que convencer um indeciso.",
            "Depois, resolva o que for prático: consultar o local de votação no aplicativo e-Título, separar um documento oficial com foto, combinar a carona da família, acompanhar quem tem setenta anos ou mais e não é obrigado a votar. Carona de parente ou vizinho pode. Transporte organizado de eleitores, ou qualquer vantagem em troca de voto, é crime eleitoral. Não dê munição para o outro lado.",
        ],
    },
    {
        "tag": "2º turno: onde trabalhar",
        "tom": "outros",
        "titulo": "Duas réguas, um mapa: onde a conversa rende e onde não rende.",
        "metrica": "{rg_robustos} de {rg_top}",
        "metrica_rot": "municípios prioritários que as duas réguas confirmam",
        "fig": C.fig_reguas,
        "fonte": "Matriz Nexus e Datafolha; regressão da urna de 2022 por município; terceira_via.json",
        "texto": [
            "Para saber onde o voto de terceira via rende, usamos duas réguas independentes. A régua das pesquisas aplica a matriz de transferência a cada município: dá a Flávio um saldo de {rg_nexus} de votos pela Nexus, ou {rg_df} com as linhas do Datafolha para Cury e Caiado. A régua da urna olha para 2022: quanto cada voto de terceira via do 1º turno rendeu a Bolsonaro entre os turnos, com efeito fixo de UF. Ela dá {rg_urna}, com intervalo de {rg_urna_lo} a {rg_urna_hi}.",
            "As duas discordam no tamanho e concordam no lugar. Onde Flávio venceu com folga no 1º turno, cada voto de terceira via rendeu a Bolsonaro {rg_folga_f} em 2022, intervalo de {rg_folga_f_lo} a {rg_folga_f_hi}. Onde Flávio perdeu com folga, rendeu {rg_folga_l}, intervalo de {rg_folga_l_lo} a {rg_folga_l_hi}: negativo. A matriz nacional não sabe onde o eleitor mora. A urna sabe.",
            "Cruzando as duas réguas, {rg_robustos} dos cem municípios prioritários pela pesquisa também estão entre os cem da urna. Esses robustos guardam {rg_robustos_estoque} de votos de terceira via. No topo da lista combinada estão {mil_comb_lista}. Em {mil_comb1}, o saldo esperado vai de {mil_comb1_piso} a {mil_comb1_teto} votos, conforme a régua.",
            "A lista completa, com os cem municípios, o piso e o teto de cada um e os dez primeiros de cada UF, está no dossiê.",
            "Juízo editorial. Concentre a conversa olho no olho onde as duas réguas concordam: capitais e cidades grandes do Centro-Sul, onde Flávio venceu e a terceira via é grande. Onde Lula venceu com folga, a militância de rua rende pouco por voto; ali o trabalho é de rede social, de palanque local e de mídia regional. E não gaste energia em Goiás antes de medir o eleitor de Caiado, porque as duas medições nacionais discordam de lado.",
            "Limite: a régua da urna é inferência ecológica, de agregado para agregado, numa eleição com outra terceira via. A régua das pesquisas usa uma matriz nacional de setembro. Quando as duas concordam, a decisão é mais segura; quando discordam, a resposta honesta é que não sabemos.",
        ],
    },
    {
        "tag": "2º turno: militância e nulo",
        "tom": "outros",
        "titulo": "O mapa da militância e o risco do voto nulo.",
        "metrica": "{mil_teto}",
        "metrica_rot": "teto endereçável local: terceira via mais o vão da direita local",
        "fig": C.fig_militancia,
        "fonte": "Urna de 2026 por município; branco e nulo de 2022 por UF; terceira_via.json",
        "texto": [
            "Somando, município a município, os {mil_estoque} de votos de terceira via e os {mil_vao} de votos que um nome do lado de Flávio, governador ou senador, teve acima dele na mesma urna, chega-se a um teto endereçável de {mil_teto}. É teto, não previsão: as duas parcelas podem contar o mesmo eleitor. Mas mostra o tamanho do território que a militância tem para trabalhar.",
            "O Nordeste pede outro método. Ali está {mil_vao_ne_pct} do vão local, {mil_vao_ne} de votos, mas Flávio venceu em municípios que guardam só {mil_ne_onde_venceu} da terceira via nordestina. Sem os governadores que não declararam apoio a ele, o vão nacional cai para {mil_vao_sem}. Juízo editorial: no Nordeste, palanque local antes de militância de rua, com os senadores eleitos do bloco que passaram Flávio na própria urna.",
            "Terceiro movimento: o eleitor de esquerda desiludido. Você não vai convencer um petista convicto a votar em Flávio, e nem deve tentar. Mas existe gente decepcionada com o governo, e para ela o nulo é uma saída honesta. Não peça voto. Peça para ela não assinar cheque em branco. Um eleitor de Lula que anula tira um voto dele; um eleitor que vira vale dois. Priorize virar. O nulo é plano B.",
            "E vigie o nulo do seu lado. Em 2022, entre os turnos, branco e nulo de presidente subiram {mil_com_delta} ponto nas UFs com 2º turno de governador e caíram {mil_sem_delta} nas outras: quem volta à urna pelo governador às vezes não escolhe presidente. Em 2026 há 2º turno estadual em {mil_risco_ufs}, com {mil_risco_comp} de votantes. Pela taxa de 2022, {mil_risco} votos em risco; {mil_rj_parcela} dos votantes dessas UFs estão no Rio de Janeiro. Case o 2º turno do governador com o de presidente.",
            "Não espalhe o mito de que muitos votos nulos anulam a eleição. Não anulam. Branco e nulo simplesmente não entram na conta. Quem mente sobre regra de eleição perde credibilidade, e credibilidade é tudo o que você tem nessa conversa.",
            "Limite: o risco do nulo é uma taxa de 2022 aplicada a 2026, numa eleição com outra terceira via. É ordem de grandeza, não previsão.",
        ],
    },
    {
        "tag": "2º turno: as frases",
        "tom": "flavio",
        "titulo": "Em vez de acusar, pergunte. Frases por eleitorado.",
        "metrica": "{nx_renan_f} × {nx_renan_l}",
        "metrica_rot": "Flávio × Lula entre os eleitores de Renan, pela Nexus",
        "fig": C.fig_frases,
        "fonte": "Nexus/BTG e Datafolha de setembro; falas com fonte em fontes_thread.json",
        "texto": [
            "Juízo editorial: este post é a recomendação da casa, com os números ao lado. Quem votou em Cury, Renan, Caiado ou Zema escolheu não votar em Flávio no 1º turno. Tinha motivo. Respeite isso. Essa pessoa foge de militante que grita, lacra e chama todo mundo de isentão. O objetivo não é fazê-la amar Flávio. É fazê-la perceber que mais quatro anos do mesmo governo é o resultado concreto de ficar em cima do muro. Faça perguntas e deixe que ela chegue sozinha à conclusão.",
            "Renan: {nx_renan_f} preferem Flávio e {nx_renan_l} Lula, pela Nexus; é o voto que mais rende, {mov_renan} de saldo. Não defenda Flávio como santo; concorde que o sistema é podre e mude a pergunta: quem você quer indicando os próximos ministros do Supremo? O próprio Renan disse na noite da eleição: {cit_renan}, segundo {cit_renan_veic}, embora não apoie ninguém. Zema: {nx_zema_f} a {nx_zema_l}, falta fechar. Ele prometeu em maio, à {cit_zema_maio_veic}, que os outros nomes {cit_zema_maio}, e disse na noite do 1º turno: {cit_zema_noite}.",
            "Cury: {nx_cury_f} a {nx_cury_l} pela Nexus, {df_cury_f} a {df_cury_l} pelo Datafolha; o maior bloco, decidido na conversa. Comece pelos filhos, não pela política: a escola do seu filho melhorou nesses anos? Alternância de poder é saúde de um país. Tom de conversa, nunca de comício. E o próprio Cury disse que {cit_cury}, segundo {cit_cury_veic}: o voto é livre, e é do seu amigo.",
            "Caiado: as medições discordam, {nx_caiado_f} a {nx_caiado_l} contra Flávio pela Nexus, {df_caiado_f} a {df_caiado_l} a favor dele pelo Datafolha. Não trate como voto garantido. Lembre que, em 2022, Caiado estava com Bolsonaro contra Lula; fale de segurança e de resultado em Goiás, não de Brasília. O PSD liberou: diretórios e militantes {cit_psd}, segundo {cit_psd_veic}. Neutralidade do partido não é neutralidade do eleitor.",
            "Em vez de acusar, pergunte. O que te faria votar contra o PT? Você confia em quem cuida do INSS hoje? Seu nulo atrapalha quem? Sua vida está mais barata hoje do que em 2022? Nos lugares, leve junto quem tem voto ali: Tarcísio em São Paulo, Cleitinho em Minas, Douglas Ruas no Rio. A conta do 2º turno favorece Flávio. Quem perde essa eleição é quem acha que ela já acabou. O dossiê completo está em brasil.arvor.co.",
        ],
    },
]
